# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ethical Roadmap
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/ethical-roadmap" # the subpath of your site, e.g. /blog
baseurl: "/" 
url: "" # `the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category

collections:
  categories:
    output: true
    permalink: /:categories/:name
  texts:
    output: false
  value_cards:
    output: false
  lenses:
    output: false
  role_cards:
    output: false
  animal_cards:
    output: false
  moral_qualities_cards:
    output: false
  provocation_cards:
    output: false
  methods_cards:
    output: false
  output_cards:
    output: false
  provocation_ds_cards:
    output: false
  glossary:
    output: false

languages:
  - name: 'English'
    key: 'en'

encoding: utf-8

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


prose:
  ignore:
    - /_animal_cards
    - /_data
    - /_includes
    - /_layouts
    - /_posts
    - /.vscode
    - /assets
    - /en
    - /js
    - /styles
    - _config.yml
    - .gitignore
    - 404.html
    - CNAME
    - Gemfile
    - Gemfile.lock
    - index.html
  metadata:
    _value_cards/english:
      - name: "ref"
        field:
          element: "text"
          label: "Refence name to the card (can not have white spaces)"
      - name: "lang"
        field: 
          element: "hidden"
          value: "en"
      - name: "sequence" 
          element: "number"
      - name: "name"
          element: "text"
          label: "Content to be displayed in the card"