# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: E-mentoring
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll_test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

defaults:
  - scope:
      path: ""
      type: mentors
    values:
      layout: mentor

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  mentors:
    output: true
    permalink: /:categories/:name
  mentor_posts:
    output: false

languages:
  - name: 'English'
    key: 'en'
  - name: 'Arabic'
    key: 'ar'

# Prose settings
prose:
  ignore:
    - .vscode
    - _data
    - _includes
    - _layouts
    - _posts
    - _sass
    - _site
    - ar
    - _assets
    - en
    - js
    - _config.yml
    - 404.html
    - about.md
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - index.html
    - LICENSE.txt
    - mentors.ar.js
    - mentors.en.js
    - README.md
  metadata:
    _mentors:
      - name: "ref"
        field:
          element: "text"
          label: Reference
    _mentors/ar:
      - name: "lang"
        field:
          element: "select"
          label: Language
          value: "ar"
          options: 
            - name: English
              value: "en"
            - name: Arabic
              value: "ar"
    _mentors/en:
      - name: "lang"
        field:
          element: "select"
          label: Language
          value: "en"
          options: 
            - name: English
              value: "en"
            - name: Arabic
              value: "ar"
    


  #rooturl: '_mentors'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
